### ISSUE TITLE
UI bugs encountered

### ISSUE THREAD

**Issue by richardtallent** [Stability-AI/ModelSpec#3]
First time user, on Mac. Noticed a few bugs:

- It's not clear for path-based fields whether they should have a trailing "/" or not (turns out no).
- Changing model, etc. paths requires restarting the whole thing. Not mentioned on screen. Refresh buttons on LoRA, etc. doesn't do the truck.
- It's complaining in the log that I don't have ffmpeg.exe. I do have ffmpeg, but it's looking for the wrong executable.

Some UI suggestions for improvement:

- Make font sizes more consistent. I have to scale text on my 30" 4K monitor, but that makes some fonts way too big.
- Many settings use TextArea fields, but are too small to actually wrap correctly when a value is entered. Give them more room by default or switch them to normal inputs.
- Ideally, now we can use File System Access API's showDirectoryPicker to have the user choose a folder! Requires user permission but easier than trying to get and paste an absolute path.
- Lots of "fit and finish" issues with padding, margins, color, text/field/icon alignment, etc. Makes the UI hard to grok.
- Add support in the cards and metadata modal for embeddings and LoRA for the JSON files that are cached by the A1111 CivitAI plugin. These have, for example, the trigger words.
- Move Sampler setting out of the comfyUI heading, it's a critical configuration setting.

The good news:

- Installed with minimum fuss
- Generates images (the most important thing!)
- Being able to use absolute or relative paths allowed me to point to my A1111 folders
- Having ComfyUI around in the background as an option is nice for future flexibility
- The built-in image viewer is nice

**Comment by mcmonkey4eva** [comment]
`It's not clear for path-based fields whether they should have a trailing "/" or not (turns out no).` shouldn't make a difference?  I wouldn't expect anything to break from having it or not, and if it does please post the specific error and I'll fix that (ie have it automatically correct).

`Changing model, etc. paths requires restarting the whole thing. Not mentioned on screen. Refresh buttons on LoRA, etc. doesn't do the truck.` yes automating the reset of the model tracker after settings change is on the todo

`It's complaining in the log that I don't have ffmpeg.exe. I do have ffmpeg, but it's looking for the wrong executable.` huh, that's from an upstream lib and it sounds like https://github.com/imageio/imageio/issues/665#issuecomment-1263237651 there might be a standing unsolved issue with mac? Stability IT sent me a macbook recently so I'll have to test that.
The comfy node that uses ffmpeg is explicitly separated from the rest as I don't trust it to reliably install, having it separate means only things that use it won't work (ie SVD video export).

`Make font sizes more consistent. I have to scale text on my 30" 4K monitor, but that makes some fonts way too big.` which text specifically is too big or too small? Mostly are all in the same size approximately, the only odd-one-out I'm aware of is the Welcome text (which is just a giant jumbotron, it's meant to be weirdly large and not really a concern if scaling makes it so big it scrolls or whatever)

`Many settings use TextArea fields, but are too small to actually wrap correctly when a value is entered. Give them more room by default or switch them to normal inputs.` Can you be more specific here? Which fields don't fit right?

`Ideally, now we can use File System Access API's showDirectoryPicker to have the user choose a folder! Requires user permission but easier than trying to get and paste an absolute path.` doesn't look to be usable https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker notably it requires HTTPS (not valid in localhost) and is considered experimental / not available in all browsers.

`Lots of "fit and finish" issues with padding, margins, color, text/field/icon alignment, etc. Makes the UI hard to grok.` That's vague/broad but I welcome PRs to improve that.

`Add support in the cards and metadata modal for embeddings and LoRA for the JSON files that are cached by the A1111 CivitAI plugin. These have, for example, the trigger words.` Can you post an example json + its filename?

`Move Sampler setting out of the comfyUI heading, it's a critical configuration setting.` yeah lol

**Comment by mcmonkey4eva** [comment]
Oh I just noticed this is the modelspec repo heh -- please post at https://github.com/Stability-AI/StableSwarmUI/issues
